/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CropPicture: typeof import('./src/components/upload/crop-picture.vue')['default']
    DatePiker: typeof import('./src/components/DatePiker.vue')['default']
    Drag: typeof import('./src/components/drag.vue')['default']
    EditorAll: typeof import('./src/components/popover/editorAll.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Message: typeof import('./src/components/popover/message.vue')['default']
    MyForm: typeof import('./src/components/popover/myForm.vue')['default']
    MyPopover: typeof import('./src/components/popover/myPopover.vue')['default']
    Popover: typeof import('./src/components/popover/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TeleportTobody: typeof import('./src/components/upload/teleport-tobody.vue')['default']
    Upload: typeof import('./src/components/upload/index.vue')['default']
    UploadPicture: typeof import('./src/components/upload/upload-picture.vue')['default']
    UrlPopover: typeof import('./src/components/popover/urlPopover.vue')['default']
  }
}
